# Generated by Django 5.0.4 on 2024-05-10 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientTypes',
            fields=[
                ('type', models.IntegerField(default=0, max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pid', models.IntegerField(default=0, max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('cid', models.IntegerField(default=0, max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('birthdate', models.DateField()),
                ('type', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='clients.clienttypes')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('oid', models.IntegerField(default=0, max_length=5, primary_key=True, serialize=False)),
                ('orderdate', models.DateField()),
                ('shippingdate', models.DateField()),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.product')),
            ],
        ),
    ]
