# Generated by Django 5.0.4 on 2024-05-10 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='type',
        ),
    ]
