# Generated by Django 5.0.4 on 2024-05-10 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_remove_client_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cid',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
