# Generated by Django 5.0.4 on 2024-05-10 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_cid'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='clients.clienttypes'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cid',
            field=models.IntegerField(default=0, max_length=5, primary_key=True, serialize=False),
        ),
    ]
