# Generated by Django 5.0.4 on 2024-05-10 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_type_alter_client_cid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientTypes',
            new_name='ClientType',
        ),
    ]
